// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id your-project-ref > types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      management_companies: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          company_name: string
          logo_url: string | null
          website: string | null
          phone: string | null
          email: string | null
          address: string | null
          city: string | null
          state: string | null
          zip: string | null
          subscription_status: string
          subscription_tier: string | null
          api_key: string | null
          verified: boolean
          metadata: Json
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          company_name: string
          logo_url?: string | null
          website?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          subscription_status?: string
          subscription_tier?: string | null
          api_key?: string | null
          verified?: boolean
          metadata?: Json
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          company_name?: string
          logo_url?: string | null
          website?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          subscription_status?: string
          subscription_tier?: string | null
          api_key?: string | null
          verified?: boolean
          metadata?: Json
        }
      }
      properties: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          address: string
          address_line_2: string | null
          city: string
          state: string
          zip: string
          latitude: number | null
          longitude: number | null
          bedrooms: number | null
          bathrooms: number | null
          square_feet: number | null
          property_type: string | null
          year_built: number | null
          rent: number
          deposit: number | null
          status: 'available' | 'coming_soon' | 'rented'
          available_date: string | null
          lease_term: string | null
          pet_policy: string | null
          pet_deposit: number | null
          smoking_allowed: boolean
          parking_type: string | null
          parking_spaces: number
          description: string | null
          amenities: Json
          images: Json
          primary_image_url: string | null
          management_company_id: string | null
          application_url: string | null
          contact_phone: string | null
          contact_email: string | null
          external_id: string | null
          verified: boolean
          verification_date: string | null
          metadata: Json
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          address: string
          address_line_2?: string | null
          city: string
          state: string
          zip: string
          latitude?: number | null
          longitude?: number | null
          bedrooms?: number | null
          bathrooms?: number | null
          square_feet?: number | null
          property_type?: string | null
          year_built?: number | null
          rent: number
          deposit?: number | null
          status?: 'available' | 'coming_soon' | 'rented'
          available_date?: string | null
          lease_term?: string | null
          pet_policy?: string | null
          pet_deposit?: number | null
          smoking_allowed?: boolean
          parking_type?: string | null
          parking_spaces?: number
          description?: string | null
          amenities?: Json
          images?: Json
          primary_image_url?: string | null
          management_company_id?: string | null
          application_url?: string | null
          contact_phone?: string | null
          contact_email?: string | null
          external_id?: string | null
          verified?: boolean
          verification_date?: string | null
          metadata?: Json
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          address?: string
          address_line_2?: string | null
          city?: string
          state?: string
          zip?: string
          latitude?: number | null
          longitude?: number | null
          bedrooms?: number | null
          bathrooms?: number | null
          square_feet?: number | null
          property_type?: string | null
          year_built?: number | null
          rent?: number
          deposit?: number | null
          status?: 'available' | 'coming_soon' | 'rented'
          available_date?: string | null
          lease_term?: string | null
          pet_policy?: string | null
          pet_deposit?: number | null
          smoking_allowed?: boolean
          parking_type?: string | null
          parking_spaces?: number
          description?: string | null
          amenities?: Json
          images?: Json
          primary_image_url?: string | null
          management_company_id?: string | null
          application_url?: string | null
          contact_phone?: string | null
          contact_email?: string | null
          external_id?: string | null
          verified?: boolean
          verification_date?: string | null
          metadata?: Json
        }
      }
      saved_properties: {
        Row: {
          id: string
          user_id: string
          property_id: string
          saved_at: string
          notes: string | null
        }
        Insert: {
          id?: string
          user_id: string
          property_id: string
          saved_at?: string
          notes?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          property_id?: string
          saved_at?: string
          notes?: string | null
        }
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      search_properties: {
        Args: {
          search_query?: string
          filter_city?: string
          filter_state?: string
          filter_status?: string[]
          min_rent?: number
          max_rent?: number
          min_beds?: number
          max_beds?: number
          min_baths?: number
          max_baths?: number
          min_sqft?: number
          max_sqft?: number
          filter_property_types?: string[]
          filter_pet_policy?: string[]
          result_limit?: number
          result_offset?: number
        }
        Returns: {
          id: string
          address: string
          city: string
          state: string
          zip: string
          bedrooms: number | null
          bathrooms: number | null
          square_feet: number | null
          property_type: string | null
          rent: number
          status: string
          primary_image_url: string | null
          management_company_id: string | null
          relevance: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
